version: "3.8"

services:
  api:
    container_name: chatbot-api-smgeo-prospec
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
